# Generated by Django 2.0.3 on 2018-03-19 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=400, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('punctuation', models.IntegerField()),
                ('stock', models.IntegerField(null=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
