# Generated by Django 2.0.3 on 2018-03-22 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
