# Generated by Django 2.0.3 on 2018-03-23 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_es',
            field=models.TextField(max_length=400, null=True),
        ),
    ]
