# Generated by Django 2.0.3 on 2018-04-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20180430_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='productos',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
