# Generated by Django 2.0.3 on 2018-04-04 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('punctuation', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.TextField(max_length=400, null=True)),
                ('address', models.TextField(max_length=400, null=True)),
                ('pc', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SaleProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.SlugField()),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='payments.Sale')),
            ],
        ),
    ]
